services:
#  rtk_app_service:
#    container_name: "rtk_app"
#    build:
#      context: .
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env

  rabbitmq_local:
    image: rabbitmq:3-management
    hostname: RTK_rabbitmq
    container_name: RTK_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  rabbitmq_test:
    image: rabbitmq:3-management
    hostname: RTK_rabbitmq_test
    container_name: RTK_rabbitmq_test
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  rabbitmq-data: